feat(languages): Add english-ngrams
max-niederman/ttyper pull request #109
Opened 2024-01-14 05:01 UTC by heysokam

Based on the app and wordlist from:
https://github.com/ranelpadon/ngram-type

2024-02-02 06:54 UTC, max-niederman requested changes
I'm not opposed to adding this dictionary, but I'm not sure about the naming. "N-gram" can refer to sequences of any kinds of symbols, including words. In fact, _all_ of our dictionaries are lists of common 1-grams, where the symbols are words. I suggest `english-nchars`, unless you have another idea.

2024-02-02 10:34 UTC, heysokam commented
They are still n-grams, not n-chars, even if they are using characters as their symbols.
The term `N-gram` for this language set is technically more correct than calling a language dataset a "unigram where each symbol is a word".
The case of ngrams symbols being words is the rare case, not the opposite.

I think the name is intuitive, and it shows up on google for the person who doesn't know what they are, and wikipedia itself gives the right description of the content _(and even explains the context of unigrams where symbols are words)_. So I would say the more intuitive and pre-existing meaning should be kept.

2024-02-05 20:43 UTC, max-niederman commented
> They are still n-grams, not n-chars, even if they are using characters as their symbols. The term `N-gram` for this language set is technically more correct than calling a language dataset a "unigram where each symbol is a word".

This is not true; neither is more technically correct because "_n_-gram" is a very broad term and applies to both. That's why I'm hesitant to call only one "_n_-gram" as its distinguishing feature.

> I think the name is intuitive, it shows up on google for the person who doesn't know what they are, and wikipedia itself gives the right description for the concept _(and even explains the context of unigrams where symbols are words)_. So I would say the more intuitive and pre-existing meaning should be kept.

This is a valid point, though. "N-gram" is more searchable, at the very least because of [ngram-type](https://github.com/ranelpadon/ngram-type). I'm going to go ahead and merge this, although in v2 I think this'll need to be replaced by _n_-gram _generation_, which is already planned.

2024-02-05 22:55 UTC, max-niederman approved these changes

2024-02-05 22:55 UTC, merged