New feature: sudden death
max-niederman/ttyper pull request #111
Opened 2024-01-22 19:56 UTC by PappasBrent

Adds an optional "sudden death mode" to `ttyper`, so that it will restart the current test as soon as the user makes a mistake.
To enable sudden death mode, start `ttyper` with the flag `--sudden-death`, e.g.:

```console
ttyper --sudden-death
```

2024-02-02 07:04 UTC, max-niederman requested changes

2024-02-02 07:04 UTC, max-niederman commented on src/main.rs
> +                    } else if test.sudden_death_enabled {
This logic should really be moved into `Test`; `test.complete` should always be `true` if the test is over, even in sudden death mode. It doesn't really make sense to put just this one part of the test logic into `main`.

2024-02-02 07:04 UTC, max-niederman commented on src/test/mod.rs
> +    event.correct == Some(false) || event.correct.is_none()
```suggestion
    event.correct != Some(true)
```
And this should probably be renamed to `ends_sudden_death` or something.

EDIT: I see now that this was copied from my implementation, lol.

2024-02-02 22:14 UTC, max-niederman approved these changes
LGTM! Thanks for the contribution.

2024-02-02 22:30 UTC, merged

2024-04-19 19:20 UTC, orhun commented
What a brutal option name! 💀